### PR TITLE
Add marker annotation for loading features

### PR DESCRIPTION
**Pull request by m9w**

### CODE REVIEW

**Comment by Pablete1234** [comment]
I wonder, why not just use @Feature for this, if the plugin.json doesn't specify a list of features then search all classes annotated with @Feature

**Comment by m9w** [comment]
Because some plugins contain draft features (with empty body), it's add flexibility of loading features. And backward compatibility.

**Comment by Pablete1234** [comment]
If the plugin has WIP feature, they can comment the `@Feature` annotation, just the same as they can simply not include this new annotation.
For backwards compat: i'd keep using the feature list from plugin.json unless it's empty, in which case we search for `@Feature`s in the base package of the plugin (which works for plugins made with new api, as for resources they should've defined one already)

**Comment by m9w** [comment]
I accept recommendation https://github.com/darkbot-reloaded/DarkBotAPI/pull/39#issuecomment-1219216962 , so this PR not required

**Pull request closed without merging**
